"""Dispute models for handling travel-related claims"""
from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey, Numeric, Boolean, JSON
from sqlalchemy.orm import relationship
from .base import Base, TimestampMixin, IDMixin


class Dispute(Base, IDMixin, TimestampMixin):
    """Dispute claim information"""
    __tablename__ = "disputes"

    # Client relationship
    client_id = Column(Integer, ForeignKey("clients.id"), nullable=False, index=True)
    client = relationship("Client", back_populates="disputes")

    # Dispute Type
    dispute_type = Column(String(50), nullable=False)
    # Types: flight_cancellation, flight_delay, lost_luggage, damaged_luggage,
    #        hotel_issue, refund_request, overbooking, service_complaint

    # Provider Information
    provider_type = Column(String(50), nullable=False)  # airline, hotel, cruise, car_rental
    provider_name = Column(String(200), nullable=False)  # Delta, Marriott, etc.

    # Incident Details
    incident_date = Column(DateTime, nullable=False)
    booking_reference = Column(String(100))
    flight_number = Column(String(20))  # If applicable
    route = Column(String(200))  # e.g., "MSP-CDG"

    # Description
    issue_description = Column(Text, nullable=False)
    passenger_names = Column(JSON, default=list)  # List of affected passengers

    # Financial Impact
    compensation_requested = Column(Numeric(10, 2))
    compensation_offered = Column(Numeric(10, 2))
    compensation_received = Column(Numeric(10, 2))
    currency = Column(String(3), default="USD")

    # Status
    status = Column(String(30), default="draft")
    # Statuses: draft, submitted, in_review, waiting_response,
    #           escalated, resolved, rejected, closed

    # Communication
    submitted_date = Column(DateTime)
    response_received_date = Column(DateTime)
    resolved_date = Column(DateTime)

    # Legal & Policy Research
    applicable_laws = Column(JSON, default=list)
    # Example: [
    #   {
    #       "regulation": "EU 261/2004",
    #       "description": "Flight delay compensation",
    #       "source_url": "...",
    #       "applicable": true
    #   }
    # ]

    airline_policy = Column(JSON, default=dict)
    # Example: {
    #   "policy_name": "Delta Contract of Carriage",
    #   "relevant_sections": ["Rule 24", "Rule 25"],
    #   "source_url": "...",
    #   "last_updated": "2024-01-01"
    # }

    # Social Media Research
    successful_strategies = Column(JSON, default=list)
    # Example: [
    #   {
    #       "source": "Reddit r/delta",
    #       "strategy": "File via EU261 form",
    #       "success_rate": "high",
    #       "link": "...",
    #       "date": "2024-01-15"
    #   }
    # ]

    # Contact Information
    contact_method = Column(String(50))  # email, phone, web_form, twitter, etc.
    contact_reference = Column(String(200))  # Email address, phone number, case number

    # Notes & Internal Communication
    notes = Column(Text)
    internal_notes = Column(Text)  # Private notes not sent to client

    # Email & Document Tracking
    source_email_id = Column(String(200))  # Gmail message ID if parsed from email

    # Relationships
    documents = relationship("DisputeDocument", back_populates="dispute", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<Dispute {self.dispute_type} - {self.provider_name} ({self.status})>"


class DisputeDocument(Base, IDMixin, TimestampMixin):
    """Documents associated with disputes"""
    __tablename__ = "dispute_documents"

    # Dispute relationship
    dispute_id = Column(Integer, ForeignKey("disputes.id"), nullable=False, index=True)
    dispute = relationship("Dispute", back_populates="documents")

    # Document Information
    document_type = Column(String(50), nullable=False)
    # Types: claim_letter, boarding_pass, receipt, email, policy_doc,
    #        response_letter, resolution_document

    filename = Column(String(255))
    file_path = Column(String(500))  # Path to stored file
    file_url = Column(String(500))  # URL if stored externally (S3, etc.)

    # Metadata
    description = Column(Text)
    mime_type = Column(String(100))
    file_size = Column(Integer)  # in bytes

    # Generated vs Uploaded
    is_generated = Column(Boolean, default=False)  # True if auto-generated by system
    generated_by = Column(String(100))  # e.g., "claim_generator_v1"

    # Status
    status = Column(String(20), default="active")  # active, archived, deleted

    def __repr__(self):
        return f"<DisputeDocument {self.document_type}: {self.filename}>"
